"use client";

import { useEffect, useMemo, useState } from "react";
import { COMPONENT_LIST, COMPONENTS } from "@/lib/game/catalog";
import { EVENTS, getEvent } from "@/lib/game/events";
import { canPlace, createSnapshot, evaluateDesign } from "@/lib/game/engine";
import { fallbackQuestions } from "@/lib/game/fallback";
import { clearSession, loadSession, saveSession } from "@/lib/game/storage";
import { downloadExhibitionPng } from "@/lib/export/png";
import type { ComponentType, EventId, GradeBand, PlacedItem, SessionState } from "@/lib/game/types";

const fresh:SessionState={teamAlias:"",memberAliases:["","",""],gradeBand:"7",step:0,items:[],advisorQuestions:[],advisorResponses:[],reflection:""};
const steps=["Hoş geldin","Takım oluştur","Görev","Tasarım","Analiz","AI danışmanı","2040 olayı","Yeniden tasarla","Sonuç raporu","Paylaş"];
const labels={climate:"Doğa ve Biyoçeşitlilik",energy:"Enerji Verimliliği",water:"Su Yönetimi",health:"Aktif Yaşam",circularity:"Döngüsel Ekonomi"};
const icons:Record<ComponentType,string>={education:"▦",sports:"◉",green:"♣",solar:"☀",rainwater:"◒",recycling:"♻",bike:"◇",shade:"♠",garden:"✿",outdoorClass:"⌂"};

export default function GameApp(){
 const [state,setState]=useState<SessionState>(fresh),[selected,setSelected]=useState<ComponentType>("education"),[rotated,setRotated]=useState(false),[active,setActive]=useState<string>(),[history,setHistory]=useState<PlacedItem[][]>([]),[notice,setNotice]=useState(""),[advisorMode,setAdvisorMode]=useState<"ai"|"fallback">("fallback"),[hydrated,setHydrated]=useState(false);
 const evaluation=useMemo(()=>evaluateDesign(state.items,state.step>=7?state.eventId:undefined),[state.items,state.eventId,state.step]);
 useEffect(()=>{queueMicrotask(()=>{const saved=loadSession();if(saved)setState({...fresh,...saved,memberAliases:saved.memberAliases??["","",""]});setHydrated(true);});},[]);
 useEffect(()=>{if(hydrated)saveSession(state);},[state,hydrated]);
 const patch=(v:Partial<SessionState>)=>setState(s=>({...s,...v})),next=(step:number)=>patch({step}),remember=()=>setHistory(h=>[...h.slice(-19),state.items.map(i=>({...i}))]);
 const cellClick=(x:number,y:number)=>{
  if(active){const old=state.items.find(i=>i.id===active);if(!old)return;const moved={...old,x,y};if(!canPlace(state.items,moved,active))return setNotice("Bu alana taşınamaz.");remember();patch({items:state.items.map(i=>i.id===active?moved:i)});setActive(undefined);return setNotice("Bileşen seçtiğiniz kareye taşındı.");}
  const d=COMPONENTS[selected],width=rotated?d.height:d.width,height=rotated?d.width:d.height,candidate:PlacedItem={id:crypto.randomUUID(),type:selected,x,y,width,height,rotated};
  if(!canPlace(state.items,candidate))return setNotice("Seçtiğiniz karede yeterli boş alan yok.");if(evaluateDesign([...state.items,candidate]).budgetUsed>100)return setNotice("Bu bileşen bütçeyi aşar.");remember();patch({items:[...state.items,candidate]});setNotice(d.label+" seçtiğiniz kareye eklendi.");
 };
 const remove=()=>{if(active){remember();patch({items:state.items.filter(i=>i.id!==active)});setActive(undefined);}},rotate=()=>{if(!active)return setRotated(v=>!v);const old=state.items.find(i=>i.id===active);if(!old)return;const changed={...old,width:old.height,height:old.width,rotated:!old.rotated};if(!canPlace(state.items,changed,active))return setNotice("Bu konumda döndürülemez.");remember();patch({items:state.items.map(i=>i.id===active?changed:i)});},undo=()=>{const p=history.at(-1);if(p){patch({items:p});setHistory(h=>h.slice(0,-1));setActive(undefined);}};
 const lock=async()=>{if(!evaluation.isValid)return setNotice("Önce görev koşullarını tamamlayın.");const snapshot=createSnapshot(state.items),local=fallbackQuestions(snapshot.evaluation,state.gradeBand);patch({initialDesign:snapshot,advisorQuestions:local,advisorResponses:local.map(()=>""),step:5});setAdvisorMode("fallback");try{const r=await fetch("/api/advisor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({gradeBand:state.gradeBand,evaluation:snapshot.evaluation})}),data=r.ok?await r.json():null;if(data?.questions?.length>=2){patch({advisorQuestions:data.questions,advisorResponses:data.questions.map(()=>""),step:5});setAdvisorMode("ai");}}catch{}};
 const drawEvent=()=>{const index=[...state.teamAlias].reduce((sum,char)=>sum+char.charCodeAt(0),state.items.length)%EVENTS.length,e=EVENTS[index];patch({eventId:e.id,step:6});},answer=(i:number,v:string)=>patch({advisorResponses:state.advisorResponses.map((x,n)=>n===i?v:x)}),reset=()=>{clearSession();setState(fresh);setHistory([]);setActive(undefined);};
 const members=state.memberAliases??["","",""],member=(i:number,v:string)=>patch({memberAliases:members.map((x,n)=>n===i?v:x)});
 if(!hydrated)return <main className="loading">Kampüs hazırlanıyor…</main>;
 return <div className="fs-app"><header className="fs-header"><Brand/><span>GELECEĞİN OKULU<br/><b>BUGÜNDEN TASARLANIR.</b></span></header>{state.step>0&&<StepTrack current={state.step}/>}<main className={state.step===3||state.step===7?"designer-layout":"screen-wrap"}>
  {state.step===0&&<Welcome onStart={()=>next(1)}/>}
  {state.step===1&&<section className="narrow-screen"><Title n="2" text="Takım Oluştur"/><div className="paper team-card"><h1>Takımını Kur</h1><label>Takım Adı<input value={state.teamAlias} onChange={e=>patch({teamAlias:e.target.value})} placeholder="Geleceğin Mimarları"/></label><label>Sınıf<select value={state.gradeBand} onChange={e=>patch({gradeBand:e.target.value as GradeBand})}>{[5,6,7,8].map(g=><option key={g}>{g}. Sınıf</option>)}</select></label><b>Takım Üyeleri (3–5 takma ad)</b>{members.map((m,i)=><div className="member-row" key={i}><span>{i+1}.</span><input value={m} onChange={e=>member(i,e.target.value)} placeholder="Takma ad"/>{members.length>3&&<button onClick={()=>patch({memberAliases:members.filter((_,n)=>n!==i)})}>×</button>}</div>)}{members.length<5&&<button className="text-btn" onClick={()=>patch({memberAliases:[...members,""]})}>+ Üye ekle</button>}<button className="green-btn" disabled={!state.teamAlias.trim()||members.filter(Boolean).length<3} onClick={()=>next(2)}>Devam Et →</button><small>Bilgiler yalnızca bu cihazda tutulur.</small></div></section>}
  {state.step===2&&<Mission onNext={()=>next(3)}/>}
  {(state.step===3||state.step===7)&&<Designer redesign={state.step===7} state={state} evaluation={evaluation} selected={selected} active={active} notice={notice} onSelect={t=>{setSelected(t);setActive(undefined)}} onCell={cellClick} onActive={setActive} onRotate={rotate} onRemove={remove} onUndo={undo} onNext={()=>next(state.step===3?4:8)}/>}
  {state.step===4&&<section className="content-screen"><Title n="5" text="Sonuçlar ve Analiz"/><div className="analysis-grid"><ScoreRing value={evaluation.scores.total}/><Metrics evaluation={evaluation}/></div>{evaluation.errors.length>0&&<div className="warning-box">{evaluation.errors.map(e=><p key={e}>! {e}</p>)}</div>}<div className="button-row"><button className="outline-btn" onClick={()=>next(3)}>← Tasarıma dön</button><button className="green-btn" disabled={!evaluation.isValid} onClick={lock}>Tasarımımı Kaydet →</button></div></section>}
  {state.step===5&&<section className="content-screen"><Title n="6" text="AI Bilim Danışmanı"/><div className="advisor-layout"><Robot/><div className="advisor-copy"><div className="speech"><b>Merhaba!</b><p>Tasarımınızı inceledim. Sizinle birkaç soru paylaşmak istiyorum.</p><small>{advisorMode==="ai"?"AI danışman aktif":"Çevrimdışı danışman aktif"}</small></div>{state.advisorQuestions.map((q,i)=><label className="question-card" key={q}><b>{q}</b><textarea value={state.advisorResponses[i]||""} onChange={e=>answer(i,e.target.value)} placeholder="Takımınızın yanıtı…"/></label>)}</div></div><button className="green-btn center-btn" disabled={state.advisorResponses.some(v=>!v.trim())} onClick={drawEvent}>Evet, değişiklik yapacağım →</button></section>}
  {state.step===6&&<EventScreen id={state.eventId!} onNext={()=>next(7)}/>}
  {state.step===8&&state.initialDesign&&<section className="content-screen report-screen"><Title n="9" text="Sonuç Raporu"/><div className="report-head"><Brand compact/><span>Takım: {state.teamAlias}<br/>Sınıf: {state.gradeBand}. Sınıf</span></div><div className="compare"><MiniPlan title="İlk Tasarım" items={state.initialDesign.placedItems}/><MiniPlan title="Son Tasarım" items={state.items}/></div><Delta before={state.initialDesign.evaluation.scores} after={evaluation.scores}/><label className="reflection-box"><b>“Tasarımımızda değiştirdiğimiz en önemli şey:”</b><textarea value={state.reflection} onChange={e=>patch({reflection:e.target.value})} placeholder="Kararınızı sayı ve gerekçeyle anlatın."/></label><div className="button-row"><button className="outline-btn" onClick={()=>next(7)}>← Yeniden düzenle</button><button className="green-btn" disabled={state.reflection.trim().length<20} onClick={()=>next(9)}>Raporu tamamla →</button></div></section>}
  {state.step===9&&state.initialDesign&&<section className="content-screen share-screen"><Title n="10" text="Paylaş ve Sergile"/><div className="celebrate">🏆</div><h1>Tebrikler!</h1><p>Sürdürülebilir bir gelecek için harika bir adım attınız.<br/>Tasarımınızı şimdi paylaşabilir ve sergiye hazırlayabilirsiniz.</p><div className="share-actions"><button onClick={()=>window.print()}>⇩ PDF Olarak İndir</button><button onClick={()=>downloadExhibitionPng({team:state.teamAlias,initial:state.initialDesign!.placedItems,final:state.items,evaluation,reflection:state.reflection,eventId:state.eventId})}>▣ Görsel Olarak İndir</button><button onClick={reset}>↻ Yeni Takım Başlat</button></div><div className="size-guide"><b>Sergi için önerilen boyutlar</b><span>A3 • 29,7 × 42 cm</span><span>50 × 50 cm • Fiziksel tasarım</span></div></section>}
 </main></div>;
}

function Brand({compact=false}:{compact?:boolean}){return <div className={"brand-logo "+(compact?"compact":"")}><svg className="brand-symbol" viewBox="0 0 50 54" aria-hidden="true"><path d="M24 51C22 36 20 24 12 10" fill="none" stroke="#168c4c" strokeWidth="2"/><path d="M22 33C4 34 1 22 4 10c13 2 21 10 18 23Z" fill="#35a653"/><path d="M23 26C22 10 31 3 44 1c1 15-6 25-21 25Z" fill="#73bd36"/><path d="M25 42c8-12 17-13 24-9-5 12-14 16-24 9Z" fill="#159151"/></svg><span className="brand-copy"><b>FutureSchool AI</b><small>2040</small></span></div>}
function StepTrack({current}:{current:number}){return <div className="step-track">{steps.map((s,i)=><span key={s} className={i<=current?"done":""}><i/><small>{s}</small></span>)}</div>}
function Title({n,text}:{n:string;text:string}){return <div className="screen-title">{n}. {text}</div>}
function Welcome({onStart}:{onStart:()=>void}){return <section className="welcome-screen"><Title n="1" text="Hoş Geldin Ekranı"/><CampusArtwork/><Brand/><p>İklim dostu, sağlıklı ve sürdürülebilir okullar için<br/>tasarla, öğren, değiştir!</p><div className="button-row"><button className="green-btn" onClick={onStart}>Göreve Başla</button><button className="outline-btn" onClick={onStart}>Nasıl Oynanır?</button></div><div className="values"><span>◌<b>Daha Temiz<br/>Bir Dünya</b></span><span>♣<b>Daha Sağlıklı<br/>Bir Gelecek</b></span><span>♙<b>Daha Güçlü<br/>Nesiller</b></span></div></section>}
function CampusArtwork(){return <div className="campus-art"><svg viewBox="0 0 760 390" role="img" aria-label="Yeşil ve sürdürülebilir okul kampüsü"><defs><linearGradient id="sky" x2="0" y2="1"><stop stopColor="#bfe6f7"/><stop offset="1" stopColor="#eef7ed"/></linearGradient><linearGradient id="grass" x2="0" y2="1"><stop stopColor="#7fb769"/><stop offset="1" stopColor="#3d7f4a"/></linearGradient><pattern id="solar" width="16" height="16" patternUnits="userSpaceOnUse"><rect width="16" height="16" fill="#276d8a"/><path d="M0 8h16M8 0v16" stroke="#8ec4d6" strokeWidth="1"/></pattern></defs><rect width="760" height="390" fill="url(#sky)"/><g fill="#6d96a8" opacity=".48"><rect x="8" y="92" width="32" height="98"/><rect x="50" y="68" width="35" height="122"/><rect x="96" y="112" width="25" height="78"/><rect x="624" y="86" width="33" height="104"/><rect x="667" y="55" width="38" height="135"/><rect x="714" y="105" width="28" height="85"/></g><path d="M0 180Q130 145 270 177T520 170T760 160V390H0Z" fill="url(#grass)"/><path d="M0 335Q200 280 390 328T760 300V390H0Z" fill="#b9c991"/><g fill="#24683d"><circle cx="52" cy="217" r="35"/><circle cx="110" cy="205" r="31"/><circle cx="670" cy="210" r="40"/><circle cx="724" cy="222" r="33"/></g><g stroke="#785a3c" strokeWidth="8"><path d="M52 220v70M110 208v66M670 214v72M724 226v64"/></g><g><path d="M155 135L375 94l195 55-220 50Z" fill="#e7efe4"/><path d="M174 145h378v151H174Z" fill="#f2ead9"/><path d="M174 145l183 50v101H174Z" fill="#d7d0bf"/><path d="M357 195l195-50v151H357Z" fill="#eee9dc"/><g fill="#5a9bab" stroke="#fff" strokeWidth="5"><rect x="196" y="183" width="55" height="55"/><rect x="272" y="201" width="55" height="55"/><rect x="383" y="188" width="55" height="61"/><rect x="460" y="170" width="55" height="61"/></g><rect x="328" y="226" width="52" height="70" fill="#5d7b73"/><path d="M214 126l145-27 105 30-144 35Z" fill="url(#solar)" stroke="#fff" strokeWidth="5"/></g><g transform="translate(525 248) rotate(-6)"><ellipse cx="83" cy="53" rx="82" ry="52" fill="#cb6255"/><ellipse cx="83" cy="53" rx="59" ry="34" fill="#5f9a58"/><path d="M83 19v68M25 53h116" stroke="#fff" strokeWidth="3"/></g><g transform="translate(51 287)"><rect width="122" height="75" rx="3" fill="url(#solar)" stroke="#dceef4" strokeWidth="5"/><path d="M61 76v17" stroke="#5b665d" strokeWidth="7"/></g><path d="M390 298c37-28 81-28 117 0-32 15-81 16-117 0Z" fill="#72a8cf"/><path d="M0 369h760" stroke="#dbe6c1" strokeWidth="12"/></svg></div>}
function Mission({onNext}:{onNext:()=>void}){return <section className="content-screen"><Title n="3" text="Görev ve Senaryo"/><h1>Göreviniz</h1><p className="lead">Yıl 2040. İstanbul’da 500 öğrencilik yeni bir okul inşa edilecek. Elinizde 10.000 m² arazi ve sınırlı bir bütçe var. İklim değişikliğine dayanıklı, sağlıklı ve sürdürülebilir bir okul tasarlayın.</p><div className="mission-stats"><span>▦<b>10.000 m²</b><small>Toplam Arazi</small></span><span>♟<b>500</b><small>Öğrenci</small></span><span>●<b>100 puan</b><small>Bütçe</small></span><span>⌂<b>2040</b><small>İklim Koşulları</small></span></div><div className="remember-box"><b>🍃 Unutma!</b><p>Her kararın, insanların, doğanın ve geleceğin üzerinde bir etkisi var.</p></div><button className="green-btn center-btn" onClick={onNext}>Tasarım Alanına Geç →</button></section>}
function Designer(p:{redesign:boolean;state:SessionState;evaluation:ReturnType<typeof evaluateDesign>;selected:ComponentType;active?:string;notice:string;onSelect:(t:ComponentType)=>void;onCell:(x:number,y:number)=>void;onActive:(id:string)=>void;onRotate:()=>void;onRemove:()=>void;onUndo:()=>void;onNext:()=>void}){return <><aside className="component-panel"><Title n={p.redesign?"8":"4"} text={p.redesign?"Yeniden Tasarla":"Tasarım Alanı (Grid)"}/><div className="category-tabs"><b>Yapılar</b><span>Doğa</span><span>Sistemler</span></div>{COMPONENT_LIST.map(c=><button key={c.type} className={"component-item "+(p.selected===c.type&&!p.active?"selected":"")} onClick={()=>p.onSelect(c.type)}><i style={{background:c.color}}>{icons[c.type]}</i><span><b>{c.label}</b><small>{c.width}×{c.height} • {c.cost} puan</small></span></button>)}</aside><section className="design-board"><div className="board-tools"><b>{p.redesign?getEvent(p.state.eventId)?.title:"10×10 Kampüs Planı"}</b><div><button onClick={p.onUndo}>↶ Geri Al</button><button onClick={p.onRotate}>↻ Döndür</button><button disabled={!p.active} onClick={p.onRemove}>Sil</button></div></div><CampusGrid items={p.state.items} active={p.active} onCell={p.onCell} onActive={p.onActive}/><p className="placement-note">{p.notice||(p.active?"Yeni konumu seçin.":"Bileşen seçin ve eklemek istediğiniz kareye dokunun.")}</p></section><aside className="live-panel"><h3>Alan Kullanımı</h3><Metrics evaluation={p.evaluation} compact/>{p.evaluation.errors.length>0&&<div className="mini-warning">{p.evaluation.errors.map(e=><p key={e}>{e}</p>)}</div>}<button className="green-btn" onClick={p.onNext}>{p.redesign?"Sonuçları Karşılaştır":"Tasarımımı Kaydet"}</button></aside></>}
function CampusGrid({items,active,onCell,onActive}:{items:PlacedItem[];active?:string;onCell:(x:number,y:number)=>void;onActive:(id:string)=>void}){return <div className="campus-grid">{Array.from({length:100},(_,i)=><button key={i} className="grid-cell" style={{gridColumn:i%10+1,gridRow:Math.floor(i/10)+1}} onClick={()=>onCell(i%10,Math.floor(i/10))} aria-label={`Kare ${i%10+1}, ${Math.floor(i/10)+1}`}/>)}{items.map(i=><button key={i.id} className={`campus-item type-${i.type} ${active===i.id?"active":""}`} style={{gridColumn:`${i.x+1}/span ${i.width}`,gridRow:`${i.y+1}/span ${i.height}`,backgroundColor:COMPONENTS[i.type].color}} onClick={()=>onActive(i.id)}><i>{icons[i.type]}</i><b>{COMPONENTS[i.type].shortLabel}</b></button>)}</div>}
function Metrics({evaluation:e,compact=false}:{evaluation:ReturnType<typeof evaluateDesign>;compact?:boolean}){return <div className={"metrics "+(compact?"compact":"")}><div className="budget"><span>Bütçe</span><b>{e.budgetUsed} / 100</b><progress max="100" value={e.budgetUsed}/></div>{(Object.keys(labels) as Array<keyof typeof labels>).map((k,i)=><div className={`metric m-${i}`} key={k}><span>{labels[k]}</span><progress max="100" value={e.scores[k]}/><b>{e.scores[k]}/100</b></div>)}</div>}
function ScoreRing({value}:{value:number}){return <div className="score-card"><h3>Sürdürülebilirlik Puanı</h3><div className="score-ring" style={{background:`conic-gradient(#168e4c ${value*3.6}deg,#dcebe1 0)`}}><span><b>{value}</b><small>/100</small></span></div><em>🍃</em></div>}
function MiniPlan({title,items}:{title:string;items:PlacedItem[]}){return <div className="mini-plan"><h3>{title}</h3><div className="campus-grid mini">{Array.from({length:100},(_,i)=><i className="grid-cell" style={{gridColumn:i%10+1,gridRow:Math.floor(i/10)+1}} key={i}/>)}{items.map(i=><span key={i.id} className="campus-item" style={{gridColumn:`${i.x+1}/span ${i.width}`,gridRow:`${i.y+1}/span ${i.height}`,background:COMPONENTS[i.type].color}}>{icons[i.type]}</span>)}</div></div>}
function Delta({before,after}:{before:ReturnType<typeof evaluateDesign>["scores"];after:ReturnType<typeof evaluateDesign>["scores"]}){return <div className="delta-box"><b>En büyük gelişimler</b>{(Object.keys(labels) as Array<keyof typeof labels>).map(k=><span key={k}>{labels[k]} <em className={after[k]>=before[k]?"positive":"negative"}>{after[k]-before[k]>=0?"+":""}{after[k]-before[k]} puan</em></span>)}</div>}
function EventScreen({id,onNext}:{id:EventId;onNext:()=>void}){const e=getEvent(id)!;return <section className="content-screen event-screen"><Title n="7" text="2040 Olay Kartı"/><HeatwaveArtwork/><h1>{e.title}</h1><p className="lead">{e.description}</p><div className="question-strip">? Okulunuz bu koşullara hazır mı? Hangi alanlarda değişiklik yapmanız gerekir?</div><button className="green-btn center-btn" onClick={onNext}>Tasarımımı Yeniden Düzenle →</button></section>}
function HeatwaveArtwork(){return <div className="event-visual"><svg viewBox="0 0 700 300" role="img" aria-label="2040 İstanbul sıcak hava dalgası"><defs><linearGradient id="heat" x2="0" y2="1"><stop stopColor="#f9c46c"/><stop offset="1" stopColor="#d46b3e"/></linearGradient></defs><rect width="700" height="300" fill="url(#heat)"/><circle cx="558" cy="70" r="43" fill="#ffe18a"/><g fill="#663d34" opacity=".8"><rect x="0" y="180" width="58" height="120"/><rect x="49" y="145" width="70" height="155"/><rect x="108" y="190" width="48" height="110"/><rect x="148" y="122" width="74" height="178"/><rect x="210" y="171" width="45" height="129"/><rect x="250" y="96" width="86" height="204"/><rect x="330" y="158" width="52" height="142"/><rect x="372" y="126" width="73" height="174"/><rect x="438" y="183" width="51" height="117"/><rect x="482" y="139" width="83" height="161"/><rect x="557" y="174" width="66" height="126"/><rect x="615" y="114" width="85" height="186"/></g><g stroke="#4e302d" strokeWidth="4"><path d="M26 300v-92M80 300V170M185 300V149M290 300V121M406 300V152M523 300V164M658 300V140"/></g><g stroke="#5f342d" strokeWidth="7"><path d="M72 72l-20-20M72 18V0M126 72l20-20M49 104H19M149 104h30"/><circle cx="99" cy="104" r="34" fill="#f5a329"/></g><text x="575" y="275" fill="#fff" fontSize="15" fontWeight="700">İSTANBUL • 2040</text></svg></div>}
function Robot(){return <svg className="robot-art" viewBox="0 0 310 390" role="img" aria-label="AI bilim danışmanı robot"><defs><linearGradient id="metal" x2="1" y2="1"><stop stopColor="#fff"/><stop offset=".6" stopColor="#dce7ed"/><stop offset="1" stopColor="#aebfca"/></linearGradient><linearGradient id="screen" x2="0" y2="1"><stop stopColor="#163c58"/><stop offset="1" stopColor="#071d31"/></linearGradient></defs><path d="M155 46V20" stroke="#365c73" strokeWidth="9"/><circle cx="155" cy="14" r="11" fill="#4cc9e7"/><g stroke="#355b72" strokeWidth="10"><path d="M76 213c-43 9-51 46-42 81" fill="none" strokeLinecap="round"/><path d="M234 213c46 12 52 47 40 78" fill="none" strokeLinecap="round"/></g><rect x="48" y="48" width="214" height="142" rx="70" fill="url(#metal)" stroke="#bccbd4" strokeWidth="7"/><rect x="67" y="68" width="176" height="101" rx="46" fill="url(#screen)"/><g fill="#65daf2"><ellipse cx="111" cy="116" rx="10" ry="18"/><ellipse cx="199" cy="116" rx="10" ry="18"/><path d="M133 140q22 18 44 0" fill="none" stroke="#65daf2" strokeWidth="7" strokeLinecap="round"/></g><path d="M80 217q75-51 150 0l-13 112H93Z" fill="url(#metal)" stroke="#355b72" strokeWidth="9"/><path d="M122 236h66v58h-66Z" rx="20" fill="#fff" stroke="#c3d1d9" strokeWidth="3"/><path d="M154 281c-15-15-28-26-19-43 15 2 23 11 19 43Z" fill="#33a454"/><path d="M155 281c5-21 18-31 33-31-2 19-12 30-33 31Z" fill="#74bb3e"/><path d="M102 329l-9 49M207 329l10 49" stroke="#355b72" strokeWidth="19" strokeLinecap="round"/><circle cx="34" cy="300" r="17" fill="url(#metal)" stroke="#355b72" strokeWidth="7"/><circle cx="275" cy="300" r="17" fill="url(#metal)" stroke="#355b72" strokeWidth="7"/></svg>}
