"use client";

import { useEffect, useMemo, useState } from "react";
import { COMPONENT_LIST, COMPONENTS } from "@/lib/game/catalog";
import { EVENTS, getEvent } from "@/lib/game/events";
import { canPlace, createSnapshot, evaluateDesign } from "@/lib/game/engine";
import { fallbackQuestions } from "@/lib/game/fallback";
import { clearSession, loadSession, saveSession } from "@/lib/game/storage";
import { downloadExhibitionPng } from "@/lib/export/png";
import type { ComponentType, EventId, GradeBand, PlacedItem, SessionState } from "@/lib/game/types";

const fresh:SessionState={teamAlias:"",memberAliases:["","",""],gradeBand:"7",step:0,items:[],advisorQuestions:[],advisorResponses:[],reflection:""};
const steps=["Hoş geldin","Takım oluştur","Görev","Tasarım","Analiz","AI danışmanı","2040 olayı","Yeniden tasarla","Sonuç raporu","Paylaş"];
const labels={climate:"Doğa ve Biyoçeşitlilik",energy:"Enerji Verimliliği",water:"Su Yönetimi",health:"Aktif Yaşam",circularity:"Döngüsel Ekonomi"};
const icons:Record<ComponentType,string>={education:"▦",sports:"◉",green:"♣",solar:"☀",rainwater:"◒",recycling:"♻",bike:"◇",shade:"♠",garden:"✿",outdoorClass:"⌂"};

export default function GameApp(){
 const [state,setState]=useState<SessionState>(fresh),[selected,setSelected]=useState<ComponentType>("education"),[rotated,setRotated]=useState(false),[active,setActive]=useState<string>(),[history,setHistory]=useState<PlacedItem[][]>([]),[notice,setNotice]=useState(""),[advisorMode,setAdvisorMode]=useState<"ai"|"fallback">("fallback"),[hydrated,setHydrated]=useState(false);
 const evaluation=useMemo(()=>evaluateDesign(state.items,state.step>=7?state.eventId:undefined),[state.items,state.eventId,state.step]);
 useEffect(()=>{queueMicrotask(()=>{const saved=loadSession();if(saved)setState({...fresh,...saved,memberAliases:saved.memberAliases??["","",""]});setHydrated(true);});},[]);
 useEffect(()=>{if(hydrated)saveSession(state);},[state,hydrated]);
 const patch=(v:Partial<SessionState>)=>setState(s=>({...s,...v})),next=(step:number)=>patch({step}),remember=()=>setHistory(h=>[...h.slice(-19),state.items.map(i=>({...i}))]);
 const cellClick=(x:number,y:number)=>{
  if(active){const old=state.items.find(i=>i.id===active);if(!old)return;const moved={...old,x,y};if(!canPlace(state.items,moved,active))return setNotice("Bu alana taşınamaz.");remember();patch({items:state.items.map(i=>i.id===active?moved:i)});setActive(undefined);return setNotice("Bileşen seçtiğiniz kareye taşındı.");}
  const d=COMPONENTS[selected],width=rotated?d.height:d.width,height=rotated?d.width:d.height,candidate:PlacedItem={id:crypto.randomUUID(),type:selected,x,y,width,height,rotated};
  if(!canPlace(state.items,candidate))return setNotice("Seçtiğiniz karede yeterli boş alan yok.");if(evaluateDesign([...state.items,candidate]).budgetUsed>100)return setNotice("Bu bileşen bütçeyi aşar.");remember();patch({items:[...state.items,candidate]});setNotice(d.label+" seçtiğiniz kareye eklendi.");
 };
 const remove=()=>{if(active){remember();patch({items:state.items.filter(i=>i.id!==active)});setActive(undefined);}},rotate=()=>{if(!active)return setRotated(v=>!v);const old=state.items.find(i=>i.id===active);if(!old)return;const changed={...old,width:old.height,height:old.width,rotated:!old.rotated};if(!canPlace(state.items,changed,active))return setNotice("Bu konumda döndürülemez.");remember();patch({items:state.items.map(i=>i.id===active?changed:i)});},undo=()=>{const p=history.at(-1);if(p){patch({items:p});setHistory(h=>h.slice(0,-1));setActive(undefined);}};
 const lock=async()=>{if(!evaluation.isValid)return setNotice("Önce görev koşullarını tamamlayın.");const snapshot=createSnapshot(state.items),local=fallbackQuestions(snapshot.evaluation,state.gradeBand);patch({initialDesign:snapshot,advisorQuestions:local,advisorResponses:local.map(()=>""),step:5});setAdvisorMode("fallback");try{const r=await fetch("/api/advisor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({gradeBand:state.gradeBand,evaluation:snapshot.evaluation})}),data=r.ok?await r.json():null;if(data?.questions?.length>=2){patch({advisorQuestions:data.questions,advisorResponses:data.questions.map(()=>""),step:5});setAdvisorMode("ai");}}catch{}};
 const drawEvent=()=>{const index=[...state.teamAlias].reduce((sum,char)=>sum+char.charCodeAt(0),state.items.length)%EVENTS.length,e=EVENTS[index];patch({eventId:e.id,step:6});},answer=(i:number,v:string)=>patch({advisorResponses:state.advisorResponses.map((x,n)=>n===i?v:x)}),reset=()=>{clearSession();setState(fresh);setHistory([]);setActive(undefined);};
 const members=state.memberAliases??["","",""],member=(i:number,v:string)=>patch({memberAliases:members.map((x,n)=>n===i?v:x)});
 if(!hydrated)return <main className="loading">Kampüs hazırlanıyor…</main>;
 return <div className="fs-app"><header className="fs-header"><Brand/><span>GELECEĞİN OKULU<br/><b>BUGÜNDEN TASARLANIR.</b></span></header>{state.step>0&&<StepTrack current={state.step}/>}<main className={state.step===3||state.step===7?"designer-layout":"screen-wrap"}>
  {state.step===0&&<Welcome onStart={()=>next(1)}/>}
  {state.step===1&&<section className="narrow-screen"><Title n="2" text="Takım Oluştur"/><div className="paper team-card"><h1>Takımını Kur</h1><label>Takım Adı<input value={state.teamAlias} onChange={e=>patch({teamAlias:e.target.value})} placeholder="Geleceğin Mimarları"/></label><label>Sınıf<select value={state.gradeBand} onChange={e=>patch({gradeBand:e.target.value as GradeBand})}>{[5,6,7,8].map(g=><option key={g}>{g}. Sınıf</option>)}</select></label><b>Takım Üyeleri (3–5 takma ad)</b>{members.map((m,i)=><div className="member-row" key={i}><span>{i+1}.</span><input value={m} onChange={e=>member(i,e.target.value)} placeholder="Takma ad"/>{members.length>3&&<button onClick={()=>patch({memberAliases:members.filter((_,n)=>n!==i)})}>×</button>}</div>)}{members.length<5&&<button className="text-btn" onClick={()=>patch({memberAliases:[...members,""]})}>+ Üye ekle</button>}<button className="green-btn" disabled={!state.teamAlias.trim()||members.filter(Boolean).length<3} onClick={()=>next(2)}>Devam Et →</button><small>Bilgiler yalnızca bu cihazda tutulur.</small></div></section>}
  {state.step===2&&<Mission onNext={()=>next(3)}/>}
  {(state.step===3||state.step===7)&&<Designer redesign={state.step===7} state={state} evaluation={evaluation} selected={selected} active={active} notice={notice} onSelect={t=>{setSelected(t);setActive(undefined)}} onCell={cellClick} onActive={setActive} onRotate={rotate} onRemove={remove} onUndo={undo} onNext={()=>next(state.step===3?4:8)}/>}
  {state.step===4&&<section className="content-screen"><Title n="5" text="Sonuçlar ve Analiz"/><div className="analysis-grid"><ScoreRing value={evaluation.scores.total}/><Metrics evaluation={evaluation}/></div>{evaluation.errors.length>0&&<div className="warning-box">{evaluation.errors.map(e=><p key={e}>! {e}</p>)}</div>}<div className="button-row"><button className="outline-btn" onClick={()=>next(3)}>← Tasarıma dön</button><button className="green-btn" disabled={!evaluation.isValid} onClick={lock}>Tasarımımı Kaydet →</button></div></section>}
  {state.step===5&&<section className="content-screen"><Title n="6" text="AI Bilim Danışmanı"/><div className="advisor-layout"><Robot/><div className="advisor-copy"><div className="speech"><b>Merhaba!</b><p>Tasarımınızı inceledim. Sizinle birkaç soru paylaşmak istiyorum.</p><small>{advisorMode==="ai"?"AI danışman aktif":"Çevrimdışı danışman aktif"}</small></div>{state.advisorQuestions.map((q,i)=><label className="question-card" key={q}><b>{q}</b><textarea value={state.advisorResponses[i]||""} onChange={e=>answer(i,e.target.value)} placeholder="Takımınızın yanıtı…"/></label>)}</div></div><button className="green-btn center-btn" disabled={state.advisorResponses.some(v=>!v.trim())} onClick={drawEvent}>Evet, değişiklik yapacağım →</button></section>}
  {state.step===6&&<EventScreen id={state.eventId!} onNext={()=>next(7)}/>}
  {state.step===8&&state.initialDesign&&<section className="content-screen report-screen"><Title n="9" text="Sonuç Raporu"/><div className="report-head"><Brand compact/><span>Takım: {state.teamAlias}<br/>Sınıf: {state.gradeBand}. Sınıf</span></div><div className="compare"><MiniPlan title="İlk Tasarım" items={state.initialDesign.placedItems}/><MiniPlan title="Son Tasarım" items={state.items}/></div><Delta before={state.initialDesign.evaluation.scores} after={evaluation.scores}/><label className="reflection-box"><b>“Tasarımımızda değiştirdiğimiz en önemli şey:”</b><textarea value={state.reflection} onChange={e=>patch({reflection:e.target.value})} placeholder="Kararınızı sayı ve gerekçeyle anlatın."/></label><div className="button-row"><button className="outline-btn" onClick={()=>next(7)}>← Yeniden düzenle</button><button className="green-btn" disabled={state.reflection.trim().length<20} onClick={()=>next(9)}>Raporu tamamla →</button></div></section>}
  {state.step===9&&state.initialDesign&&<section className="content-screen share-screen"><Title n="10" text="Paylaş ve Sergile"/><div className="celebrate">🏆</div><h1>Tebrikler!</h1><p>Sürdürülebilir bir gelecek için harika bir adım attınız.<br/>Tasarımınızı şimdi paylaşabilir ve sergiye hazırlayabilirsiniz.</p><div className="share-actions"><button onClick={()=>window.print()}>⇩ PDF Olarak İndir</button><button onClick={()=>downloadExhibitionPng({team:state.teamAlias,initial:state.initialDesign!.placedItems,final:state.items,evaluation,reflection:state.reflection,eventId:state.eventId})}>▣ Görsel Olarak İndir</button><button onClick={reset}>↻ Yeni Takım Başlat</button></div><div className="size-guide"><b>Sergi için önerilen boyutlar</b><span>A3 • 29,7 × 42 cm</span><span>50 × 50 cm • Fiziksel tasarım</span></div></section>}
 </main></div>;
}

function Brand({compact=false}:{compact?:boolean}){return <div className={"brand-logo "+(compact?"compact":"")}><span className="leaves"><i/><i/><i/></span><span><b>FutureSchool AI</b><small>2040</small></span></div>}
function StepTrack({current}:{current:number}){return <div className="step-track">{steps.map((s,i)=><span key={s} className={i<=current?"done":""}><i/><small>{s}</small></span>)}</div>}
function Title({n,text}:{n:string;text:string}){return <div className="screen-title">{n}. {text}</div>}
function Welcome({onStart}:{onStart:()=>void}){return <section className="welcome-screen"><Title n="1" text="Hoş Geldin Ekranı"/><div className="campus-art"><div className="skyline"/><div className="school"><i/><i/><i/></div><div className="track"/><div className="trees">♣ ♣ ♣ ♣ ♣ ♣ ♣</div></div><Brand/><p>İklim dostu, sağlıklı ve sürdürülebilir okullar için<br/>tasarla, öğren, değiştir!</p><div className="button-row"><button className="green-btn" onClick={onStart}>Göreve Başla</button><button className="outline-btn" onClick={onStart}>Nasıl Oynanır?</button></div><div className="values"><span>◌<b>Daha Temiz<br/>Bir Dünya</b></span><span>♣<b>Daha Sağlıklı<br/>Bir Gelecek</b></span><span>♙<b>Daha Güçlü<br/>Nesiller</b></span></div></section>}
function Mission({onNext}:{onNext:()=>void}){return <section className="content-screen"><Title n="3" text="Görev ve Senaryo"/><h1>Göreviniz</h1><p className="lead">Yıl 2040. İstanbul’da 500 öğrencilik yeni bir okul inşa edilecek. Elinizde 10.000 m² arazi ve sınırlı bir bütçe var. İklim değişikliğine dayanıklı, sağlıklı ve sürdürülebilir bir okul tasarlayın.</p><div className="mission-stats"><span>▦<b>10.000 m²</b><small>Toplam Arazi</small></span><span>♟<b>500</b><small>Öğrenci</small></span><span>●<b>100 puan</b><small>Bütçe</small></span><span>⌂<b>2040</b><small>İklim Koşulları</small></span></div><div className="remember-box"><b>🍃 Unutma!</b><p>Her kararın, insanların, doğanın ve geleceğin üzerinde bir etkisi var.</p></div><button className="green-btn center-btn" onClick={onNext}>Tasarım Alanına Geç →</button></section>}
function Designer(p:{redesign:boolean;state:SessionState;evaluation:ReturnType<typeof evaluateDesign>;selected:ComponentType;active?:string;notice:string;onSelect:(t:ComponentType)=>void;onCell:(x:number,y:number)=>void;onActive:(id:string)=>void;onRotate:()=>void;onRemove:()=>void;onUndo:()=>void;onNext:()=>void}){return <><aside className="component-panel"><Title n={p.redesign?"8":"4"} text={p.redesign?"Yeniden Tasarla":"Tasarım Alanı (Grid)"}/><div className="category-tabs"><b>Yapılar</b><span>Doğa</span><span>Sistemler</span></div>{COMPONENT_LIST.map(c=><button key={c.type} className={"component-item "+(p.selected===c.type&&!p.active?"selected":"")} onClick={()=>p.onSelect(c.type)}><i style={{background:c.color}}>{icons[c.type]}</i><span><b>{c.label}</b><small>{c.width}×{c.height} • {c.cost} puan</small></span></button>)}</aside><section className="design-board"><div className="board-tools"><b>{p.redesign?getEvent(p.state.eventId)?.title:"10×10 Kampüs Planı"}</b><div><button onClick={p.onUndo}>↶ Geri Al</button><button onClick={p.onRotate}>↻ Döndür</button><button disabled={!p.active} onClick={p.onRemove}>Sil</button></div></div><CampusGrid items={p.state.items} active={p.active} onCell={p.onCell} onActive={p.onActive}/><p className="placement-note">{p.notice||(p.active?"Yeni konumu seçin.":"Bileşen seçin ve eklemek istediğiniz kareye dokunun.")}</p></section><aside className="live-panel"><h3>Alan Kullanımı</h3><Metrics evaluation={p.evaluation} compact/>{p.evaluation.errors.length>0&&<div className="mini-warning">{p.evaluation.errors.map(e=><p key={e}>{e}</p>)}</div>}<button className="green-btn" onClick={p.onNext}>{p.redesign?"Sonuçları Karşılaştır":"Tasarımımı Kaydet"}</button></aside></>}
function CampusGrid({items,active,onCell,onActive}:{items:PlacedItem[];active?:string;onCell:(x:number,y:number)=>void;onActive:(id:string)=>void}){return <div className="campus-grid">{Array.from({length:100},(_,i)=><button key={i} className="grid-cell" style={{gridColumn:i%10+1,gridRow:Math.floor(i/10)+1}} onClick={()=>onCell(i%10,Math.floor(i/10))} aria-label={`Kare ${i%10+1}, ${Math.floor(i/10)+1}`}/>)}{items.map(i=><button key={i.id} className={`campus-item type-${i.type} ${active===i.id?"active":""}`} style={{gridColumn:`${i.x+1}/span ${i.width}`,gridRow:`${i.y+1}/span ${i.height}`,backgroundColor:COMPONENTS[i.type].color}} onClick={()=>onActive(i.id)}><i>{icons[i.type]}</i><b>{COMPONENTS[i.type].shortLabel}</b></button>)}</div>}
function Metrics({evaluation:e,compact=false}:{evaluation:ReturnType<typeof evaluateDesign>;compact?:boolean}){return <div className={"metrics "+(compact?"compact":"")}><div className="budget"><span>Bütçe</span><b>{e.budgetUsed} / 100</b><progress max="100" value={e.budgetUsed}/></div>{(Object.keys(labels) as Array<keyof typeof labels>).map((k,i)=><div className={`metric m-${i}`} key={k}><span>{labels[k]}</span><progress max="100" value={e.scores[k]}/><b>{e.scores[k]}/100</b></div>)}</div>}
function ScoreRing({value}:{value:number}){return <div className="score-card"><h3>Sürdürülebilirlik Puanı</h3><div className="score-ring" style={{background:`conic-gradient(#168e4c ${value*3.6}deg,#dcebe1 0)`}}><span><b>{value}</b><small>/100</small></span></div><em>🍃</em></div>}
function MiniPlan({title,items}:{title:string;items:PlacedItem[]}){return <div className="mini-plan"><h3>{title}</h3><div className="campus-grid mini">{Array.from({length:100},(_,i)=><i className="grid-cell" style={{gridColumn:i%10+1,gridRow:Math.floor(i/10)+1}} key={i}/>)}{items.map(i=><span key={i.id} className="campus-item" style={{gridColumn:`${i.x+1}/span ${i.width}`,gridRow:`${i.y+1}/span ${i.height}`,background:COMPONENTS[i.type].color}}>{icons[i.type]}</span>)}</div></div>}
function Delta({before,after}:{before:ReturnType<typeof evaluateDesign>["scores"];after:ReturnType<typeof evaluateDesign>["scores"]}){return <div className="delta-box"><b>En büyük gelişimler</b>{(Object.keys(labels) as Array<keyof typeof labels>).map(k=><span key={k}>{labels[k]} <em className={after[k]>=before[k]?"positive":"negative"}>{after[k]-before[k]>=0?"+":""}{after[k]-before[k]} puan</em></span>)}</div>}
function EventScreen({id,onNext}:{id:EventId;onNext:()=>void}){const e=getEvent(id)!;return <section className="content-screen event-screen"><Title n="7" text="2040 Olay Kartı"/><div className={`event-visual event-${id}`}><span>{e.icon}</span><i>İSTANBUL • 2040</i></div><h1>{e.title}</h1><p className="lead">{e.description}</p><div className="question-strip">? Okulunuz bu koşullara hazır mı? Hangi alanlarda değişiklik yapmanız gerekir?</div><button className="green-btn center-btn" onClick={onNext}>Tasarımımı Yeniden Düzenle →</button></section>}
function Robot(){return <div className="robot" aria-label="AI bilim danışmanı"><div className="antenna"/><div className="robot-head"><i>•</i><b>⌣</b><i>•</i></div><div className="robot-body">🍃</div><span className="arm left"/><span className="arm right"/><span className="leg left"/><span className="leg right"/></div>}
